services:
  - type: web
    name: formulaire-cetelm
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 app:app
    envVars:
      - key: PORT
        value: "10000"
